name: Check latest MTGA version on commit
on:
  push

jobs:
  buildjob:
    name: Get latest MTGA version
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm install
        working-directory: ./.github/actions/check-version-action
      - uses: ./.github/actions/check-version-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v1
        with:
          repository: riQQ/MsiExtractor
          ref: refs/heads/master
          path: MsiExtractor
          fetch-depth: 1
      - run: |
          echo $Env:GITHUB_WORKSPACE
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\..\MsiExtractor\MsiExtractor.sln
