name: Check latest MTGA version on commit
on:
  push

jobs:
  buildjob:
    name: Get latest MTGA version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm install
        working-directory: ./.github/actions/check-version-action
      - run: npm run build
        working-directory: ./.github/actions/check-version-action
      - uses: ./.github/actions/check-version-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}