name: Check latest MTGA version on commit
on:
  push

jobs:
  buildjob:
    name: Get latest MTGA version
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm install
        working-directory: ./.github/actions/check-version-action
      - id: get_version
        uses: ./.github/actions/check-version-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v1
        with:
          repository: riQQ/MsiExtractor
          ref: refs/heads/master
          path: MsiExtractor
          fetch-depth: 1
      - run: |
          echo $Env:GITHUB_WORKSPACE
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\..\MsiExtractor\MsiExtractor.sln
      - id: download_msi
        run: |
          $msiUrl = ${{ steps.get_version.outputs.msiUrl }}
          echo $msiUrl
          $fileName = (([uri]$msiUrl).Segments)[-1]
          echo $fileName
          $msiFilePath = "$Env:GITHUB_WORKSPACE\..\$fileName"
          echo $msiFilePath
          (New-Object System.Net.WebClient).DownloadFile($msiUrl, $msiFilePath)
          echo "::set-output name=msiFilePath::$msiFilePath"
      - name: Run MsiExtractor
        run: |
          cd "$Env:GITHUB_WORKSPACE\..\MsiExtractor\MsiExtractor\bin\Debug"
          .\MsiExtractor.exe ${{ steps.download_msi.outputs.msiFilePath }} "Wizards.MDN.GreProtobuf.Unity.dll"
      - name: Checkout proto extractor
        uses: actions/checkout@v1
        with:
          repository: riQQ/proto-extractor
          ref: refs/heads/mtgatool-formatting
          path: proto-extractor
          fetch-depth: 1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.805' # SDK Version to use
      - run: |
          cd "$Env:GITHUB_WORKSPACE\..\proto-extractor\extractor
          dotnet build
